### PR TITLE
Fixes: #18  network check for regtest

### PR DESCRIPTION
**Pull request by notmandatory**

### CODE REVIEW

**Comment by notmandatory** [comment]
I tested this with jimpo's bip157-net [branch](https://github.com/jimpo/bitcoin/tree/bip157-net) using my own little docker-compose [regtest net project](https://github.com/notmandatory/bitcoin-regtest-box).

**Review by ZmnSCPxj — COMMENTED** [review]
This seems to paper over the problem?  Why is `master_account.master_public().network` not `Network::Regtest` in this case?

**Comment by ZmnSCPxj** [comment]
Also you can put the text "Fixes: #18" in your description so that if this gets merged, the issue is automatically closed.

**Comment by notmandatory** [comment]
Thanks, I'm not very familiar with github tricks, but I knew there was some way to do it.  Should I ping someone to help review or just wait for folks to get to it whenever?

**Comment by ZmnSCPxj** [comment]
Well, I do not know the details of defiads, honestly, and apparently this has to do as well with a library we use here rather than with our own code.  Personally, if the issue is in some infelicity of the library, then I think we should work around it by wrapping the call to the library and putting the workaround there, rather than mess with our assertions elsewhere in the code.  Anyway @philbertw4 is probably more familiar with the code at this point than I am.

**Comment by philbertw4** [comment]
> This seems to paper over the problem? Why is `master_account.master_public().network` not `Network::Regtest` in this case?

I believe that the reason for this is due to the fact that `master_account` is created by decoding some information which was stored in `~/.defiads/regtest/defiads.cfg` or `~/.defiads/testnet/defiads.cfg`. Which directory is chosen depends on the `--bitcoin-network` flag being passed in. That flag is what is checked by the variable `bitcoin_network` in the code that @notmandatory added here. So I *think*, but am by no means certain, that this does actually solve the problem while still preserving the benefits of having a check.

The eventual solution it seems would be to also include in the `defiads.cfg` files some network-specific information. As it stands right now, the code extracts that network information from how the ECC private key is encoded/stored in the .cfg file.

**Comment by ZmnSCPxj** [comment]
If we have control over the code that makes `defiads.cfg` I think it would be preferable to fix this *now* and add the network information explcitly there

**Comment by philbertw4** [comment]
> If we have control over the code that makes `defiads.cfg` I think it would be preferable to fix this _now_ and add the network information explcitly there

Yeah, I agree. However, at this juncture, my rust skills and familiarity with the code are not quite there to make that change.

**Comment by ZmnSCPxj** [comment]
Well if we go this way, we should at least make a note in the source code:


    /* We should really just assert_eq! bitcoin_network and the wallet network,
     * but currently the defiads.cfg does not differentiate between testnet and
     * regtest.  FIXME: Have defiads.cfg know the difference between
     * regtest and testnet.
     */

**Comment by notmandatory** [comment]
@ZmnSCPxj I don't think it's a problem with the rust-bitcoin library, but just in the way this project is using xpubs to determine the network the wallet was created for. Both testnet and regtest use the same magic number in the xpub [encoding per bip32](https://en.bitcoin.it/wiki/BIP_0032#Serialization_format).

That said, I agree it makes sense to add the network to the defiads.cfg, I'll update this PR.

**Comment by stevenroose** [comment]
I'm not exactly aware of the details of this change, but it's correct that Bitcoin doesn't differentiate Testnet and Regtest in many places. [BIP32 prefixes](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/bip32.rs#L582) is one of them, as are [legacy address prefixes](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/address.rs#L374).

**Comment by notmandatory** [comment]
@stevenroose this PR is only to the defiads/main.rs binary, not the lib, it has two commits:

1. updates an existing assert to verify that if the network is regtest the xpub must be network testnet. It was failing this check before when used with --bitcoin-network regtest.

2. when a new wallet is created it adds a "network" property to the ~/.defiads/<network>/defiads.cfg toml file, and then asserts this network matches the --bitcoin-network parameter when the bin is restarted.

We need commit 1 to allow regtest testing, commit 2 just tightens things up a little and would prevent a testnet wallet from being used in regtest mode, or the other way around.

**Review by ZmnSCPxj — APPROVED** [review]
ACK 9ee1a6749df154380b3b093cd19cdd7e8ccd3b0e

Looks fine to me.  Probably we should make a "proper" error report to the user and exit, but this should be fine for now.

**Comment by notmandatory** [comment]
Thanks!

**Pull request merged**
