### PR TITLE
Add Cargo.lock

### PR DESCRIPTION
**Pull request by jonasnick**
Without Cargo.lock checked in I can't create a nix package with the usual `buildRustPackage` mechanism. Also as per https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries this is recommended for rust binaries.

### CODE REVIEW

**Comment by tamasblummer** [comment]
Thank Jonas! It is too early to package this as dependencies are not published yet, I will return to this issue.

**Comment by jonasnick** [comment]
updated

**Comment by ZmnSCPxj** [comment]
Pardon my Rust ignorance but what exactly are the ramifications of this?  A non-comprehensive random sampling from github shows about 1/3 of Rust repositories have a Cargo.lock when they have a Cargo.toml (I filtered out repos that had no Cargo.toml at all), so this seems plausible to add, but I am a complete Rust n00b.

**Comment by jonasnick** [comment]
From the link above:
 > The purpose of a Cargo.lock is to describe the state of the world at the time of a successful build. It is then used to provide deterministic builds across whatever machine is building the package by ensuring that the exact same dependencies are being compiled. [...] it is recommended that all binaries check in their Cargo.lock.

Could be that the 1/3 you found is a result of 1/3 being binaries.

**Comment by philbertw4** [comment]
Also a Rust n00b here. In an effort to get a local build environment up and running for this project, I noticed that when running `cargo build --release` the project builds successfully.

However, when opening the project in my editor (trying out VS Code which seems fine so far), it warns me of the following issue in db.rs:
```
no variant or associated item named `Recommended` found for type `bitcoin_wallet::account::MasterKeyEntropy` in the current scope

variant or associated item not found in `bitcoin_wallet::account::MasterKeyEntropy`
```
So, oddly, the editor, which uses the rust language server extension, seems to have caught something that didn't get caught in the manual build. Specifically, it seems that the bitcoin wallet library used by defiads renamed `MasterKeyEntropy::Recommended` to `MasterKeyEntropy::Double` as seen by this commit: https://github.com/rust-bitcoin/rust-wallet/commit/c822608850d3e39ad2ee43de494539da7557f550#diff-d6ba02201983ce915e1b9b284b5e517c

Is this the type of thing that having a `Cargo.lock` checked in will help us avoid?

**Comment by stevenroose** [comment]
Any reason you didn't run cargo update before committing?

Some of them are probably worth it to update:
```
+ "bitcoin_hashes 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)",
+ "rand 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)",
+ "bitcoin-wallet 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
```

**Comment by ZmnSCPxj** [comment]
> Any reason you didn't run cargo update before committing?

Probably because the PR was opened a few months ago and had 0 activity afterwards, so....

**Comment by stevenroose** [comment]
Ah yeah sure. Well, we can update this later. With rust-bitcoin v0.23.0 which might be worth to have as well, but will take some work to change types.

**Pull request merged**
