### PR TITLE
renames the entropy variant to be consistent

### PR DESCRIPTION
**Pull request by philbertw4**
with the underlying bitcoin wallet rust library

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
Given #7 perhaps this should be put in the same PR as well? My basic understanding of cargo is that this `Cargo.lock` indicates exactly what version of our dependencies to be used, so the exact name might depend on what `Cargo.lock` we end up having...? @jonasnick

**Comment by philbertw4** [comment]
Yes, I think I'm starting to understand that now too. I added the copy of `Cargo.lock` from my local copy that I just built (after running a `cargo update`). Hopefully I have that right?

**Comment by ZmnSCPxj** [comment]
Let's give @jonasnick a day or so to review the `Cargo.lock`, then if no objection from him we can merge this and close #7 in favor of this.

**Comment by stevenroose** [comment]
Oh. I just merged the `Cargo.lock` file from Jonas. I guess if there is an inconsistency, @philbertw4 can rebase this PR and propose an update to `Cargo.lock` instead.

**Comment by philbertw4** [comment]
Of note: I think this PR spawned from my rust n00b skills in that I had run `cargo update` locally, which caused the inconsistency and hence I committed a new `Cargo.lock` file. I have no reason o prefer the new `Cargo.lock` file (and fixing this associated variable/pattern-matching error) over the one currently in the master branch. So this PR may be completely irrelevant at the moment and may be closed.

**Pull request closed without merging**
